#pragma once

#include "gfx.h"

/* Icons generated by tools/imggen.py from MaterialIcons-Regular.ttf, WeatherIcons-Regular.ttf (see THIRD_PARTY.md). */
extern const gfx_bitmap_t gfx_icon_t5_thermometer_40;
