#pragma once

#include <stdint.h>

/* Bitmap font generated by tools/fontgen.py (spec §4.4, T5 spec §6.3). */
typedef struct {
    uint32_t codepoint;
    uint32_t offset;  /* into gfx_font_t.bitmap */
    uint16_t width;   /* bitmap width in px */
    uint16_t height;  /* bitmap height in px */
    int16_t x_offset; /* left edge relative to the pen */
    int16_t y_offset; /* top edge relative to the baseline; negative is above */
    uint16_t advance; /* pen advance in px */
} gfx_glyph_t;

typedef struct {
    const uint8_t *bitmap;     /* glyph rows, each padded to whole bytes: at 1 bpp MSB first, 1 = ink; at 4 bpp
                                * two pixels a byte, the first in the high nibble, coverage 0-15 */
    const gfx_glyph_t *glyphs; /* sorted by codepoint */
    uint16_t glyph_count;
    uint16_t ascent;      /* baseline distance from the top of a line */
    uint16_t line_height; /* ascent + descent */
    uint8_t bpp;          /* 1 or 4; 0 (an initializer without it) reads as 1 */
} gfx_font_t;
